sensor_kit_base_link2Pandar40P:
  x: 0.9
  y: 0.0
  z: 2.0
  roll: 0.0
  pitch: 0.0
  yaw: 3.1437
sensor_kit_base_link2imu:
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 3.141592
  pitch: 0.0
  yaw: 0.0
sensor_kit_base_link2gps:
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
